### PR TITLE
Dockerize 

### PR DESCRIPTION
**Pull request by mfouad**
Dockerfile for client.

- I expect developers need to do some advanced stuff like pulling depednencies from git and so, so it used the full node.js image, not the slim one
- There is not package.lock.json yet, so I use "npm install"
- Uses Environment variables to modify build behaviour. this will need improvement once the configuration paramerts mature and are clear.
- I had to pin dependencies that use aframe and three.js from github. to make the build reproducable, so production releases will not use the bleeding edge from master.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Yesss awesome!

**Comment by mfouad** [comment]
Please note that this does not build .. based on latest from Master. I had to test using latest from aframe-components branch to test that it builds.

**Comment by dmitrizagidulin** [comment]
@mfouad can you add a brief section to the README with instructions (on how to run the image, what port it'll be exposed on, etc).

**Comment by mfouad** [comment]
@dmitrizagidulin instructions added
please check https://github.com/xrchat/xrchat-ops for the compose file

**Comment by dmitrizagidulin** [comment]
Perfect, thanks @mfouad!

**Pull request merged**
