### PR TITLE
PR - Combine Login and Magic Link components #75

### PR DESCRIPTION
**Pull request by green9016**

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Addresses issue #75.

**Comment by thatpassesfor** [comment]
reviewing.

**Comment by dmitrizagidulin** [comment]
(rebased on latest `dev` to fix `yarn build` error.)

**Comment by thatpassesfor** [comment]
SMS Login link needs a checkbox to terms and conditions (all login methods need that)

**Comment by thatpassesfor** [comment]
image

Phone number will not need a valid email address.

**Comment by dmitrizagidulin** [comment]
Merging into `dev` for testing on dev server.

**Pull request merged**
