### PR TITLE
added /portals along with dynamic routing

### PR DESCRIPTION
**Pull request by campbellgoe**
Solves #53 and #14

It should be noted that it does not fully satiate issue #14 - which has a larger scope than this pull request.

Additionally, the way assets are loaded could be made much more efficient. This can wait until a further PR.

This PR contains two new pages `/portals` and `/portaltest` containing `a-link` entities. Clicking a portal will take you to that portal's page, without reloading Aframe, because it is using `next/router` to dynamically change the route.

Additionally, scene data for specific pages (in this case our portal and portaltest pages) is passed into the `SceneRoot` component as children and rendered inside an `aframe-react` `Scene`. As the user changes page dynamically, the children inside `SceneRoot` changes, but the rest of the JSX remains the same, so that it only renders the changes between pages.

The routing issue was that using `next/router` or `next/link` would cause pages to break as you navigated (causing White Screen of Death), and this was most likely due to bugs found in the assets code, such as using `<a-assets>` instead of `<Entity primitive="a-assets">`.

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
@campbellgoe looks good. Two questions - 1) do you mind resolving the merge conflicts? (I took a look at em, but I don't understand enough about that file to tell how to resolve em.)
2) How would I go about testing this? (if that's applicable)

**Comment by campbellgoe** [comment]
OK, I've fixed the merge conflict.

To test you can:
1. Go to `localhost:3000/portals`
2. Confirm you see a portal with '/portaltest' above it.
3. Click the portal.
4. Confirm the URL changes to '/portaltest' and that you can see a portal again but with the text '/portals' above it (It may take a second to load). If you look carefully you should also be able to see that the navigation bar at the top doesn't unload and reload, but remains there.
5. Click the portal back to '/portals' and repeat these steps a few times, to confirm no WSOD occurs.

It would be great if we integrated some sort of automated testing, maybe Cypress or Puppeteer, for this test - then anytime someone changed something that could potentially break routing, the test would catch it.

**Comment by dmitrizagidulin** [comment]
@mohrtw  hmm I think this is good enough to merge. And let's open a separate ticket to implement support for external portals?

**Comment by mohrtw** [comment]
Sounds good

**Comment by campbellgoe** [comment]
Good point. For external links we don't want to use next/router, and instead can use the a-link built in navigation functionality. So the fix will involve editing Portal.tsx to pass href to a-link if it's external. We can simply check if the href is internal or external with some function. I'll start on that now.

**Pull request merged**
